# -*- coding: utf-8 -*-
"""LGMVIP-Python-Task No:4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xoOV-6ZOfJ49J31AWBHjOawzUkScRnmA
"""



def greet():
    print("Hello! I am your Placement Assistant chatbot. How can I help you with placements today?")


def get_response(user_input):

    responses = {
        "hello": "Hi there! How can I assist you with placements?",
        "hi": "Hello! What do you need help with regarding placements?",
        "how are you": "I'm just a bot, but I'm here to help you with placement queries!",
        "bye": "Goodbye! Good luck with your placements!",
        "help": "Sure, I'm here to help! What do you need assistance with regarding placements?",
        "companies": "We have many companies visiting for placements like Google, Microsoft, Amazon, and more. Do you want details about a specific company?",
        "interview tips": "Here are some tips: 1. Understand the company and role. 2. Practice common interview questions. 3. Be confident and clear in your responses.",
        "placement statistics": "The placement statistics for the last year: 95% of students were placed. Average package: $70,000. Highest package: $150,000.",
        "resume tips": "Make sure your resume is clear and concise. Highlight your skills and achievements. Tailor it for each job application.",
        "mock interviews": "You can schedule mock interviews with our career services. They help you practice and get feedback.",
        "application process": "The application process typically includes submitting your resume, attending pre-placement talks, and going through several rounds of interviews.",
        "internships": "Internships are a great way to gain experience. Many companies offer internships as part of their placement programs.",
        "eligibility criteria": "Eligibility criteria vary by company. Generally, companies look at your academic performance, skills, and sometimes extracurricular activities.",
        "technical skills": "Common technical skills required include programming languages like Python, Java, and C++, along with knowledge of data structures and algorithms."
    }


    user_input = user_input.lower()

    if user_input in responses:
        return responses[user_input]
    else:
        return "I'm not sure how to respond to that. Can you ask something else about placements?"
def chatbot():
    greet()
    while True:
        user_input = input("You: ")
        if user_input.lower() == "bye":
            print("Chatbot: Goodbye! Good luck with your placements!")
            break
        response = get_response(user_input)
        print(f"Chatbot: {response}")


chatbot()

